from typing import Protocol

from domain.models.user import User
from domain.models.user_id import UserId


class UserReader(Protocol):
    async def get_by_id(self, user_id: UserId) -> User: ...
    async def is_in_database(self, user_id: UserId) -> bool: ...


class UserReadWrite(UserReader, Protocol):
    async def add_user(self, user: User) -> None: ...
    async def remove_user(self, user_id: UserId) -> None: ...
    async def promote_user(self, user_id: UserId) -> None: ...
    async def demote_user(self, user_id: UserId) -> None: ...
    async def add_known_name(self, name: str, user_id: UserId) -> None: ...
